title: Jonathan Spengeman
email: jonathan.spengeman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on software development by Jonathan Spengeman.
baseurl: ""
url: "https://jspengeman.com"
email: "jonathan.spengeman@gmail.com"
stackoverflow_url: "https://stackoverflow.com/users/8112353/jonathan-spengeman"
instagram_url: "https://www.instagram.com/jspengy/"
github_url:  "https://github.com/jspengeman"

permalink: /:title
paginate_path: "/page-:num/"
paginate: 5

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock

sass:
    style: compressed

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true
